trainer_type: zlm_hybrid

dataset:
    name: fineweb-100BT-split-128
    branch: main

    type: split
    kwargs: {}

bs: 64
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 1000
    num_training_steps: 50000

    lr: 0.00005
    final_lr: 0.000016

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

    grad_clip: 3.0

checkpoint_interval: 2500
save_optimizer: false

init_hooked: false
init_hooked_steps: 0

acc_hook: 0.75
hook_warmup_steps: 1000

upper_acc_bound: 0.80
lower_acc_bound: 0.70

upper_lm_bound: 0.75
lower_lm_bound: 0.50

base_alpha: 10.0
alpha_steps: 10000

kl_weight_threshold: 0.1
kl_scale: 0.1

log_image_interval: 100
