trainer_type: zlm_asym

dataset:
    name: fineweb-100BT-split-128
    branch: split-2

    type: split
    kwargs: {}

bs: 64
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 1000
    num_training_steps: 50000

    lr: 0.000025
    final_lr: 0.0000025

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

    grad_clip: 3.0

checkpoint_interval: 2500
save_optimizer: false

init_hooked: true
init_hooked_steps: 1000000

acc_hook: 0.75
hook_warmup_steps: 5000

upper_acc_bound: 0.95
lower_acc_bound: 0.90

upper_lm_bound: 0.75
lower_lm_bound: 0.50

kl_scale: 0.1

log_image_interval: 100
