trainer_type: zlm

ds_type: split
ds_kwargs: {}

bs: 4
num_epochs: 10000

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 10
    num_training_steps: 5000

    lr: 0.0001
    final_lr: 0.000001

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

checkpoint_interval: 1000
save_optimizer: false

kl_weight: 0.1
