trainer_type: zlm

dataset:
    name: fineweb-100BT-split-128
    branch: split-2

    type: zae
    kwargs:
        checkpoint_path: local_data/proto-zlm_zae-beta/000000030000

bs: 64
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 1000
    num_training_steps: 50000

    lr: 0.00005
    final_lr: 0.000005

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

checkpoint_interval: 5000
save_optimizer: false

noise_scale_steps: null

running_beta: 0.9

log_image_interval: 100
