trainer_type: zlm

dataset:
    name: fineweb-100BT-split-128
    branch: main

    type: split
    kwargs: {}

bs: 128
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 1000
    num_training_steps: 50000

    lr: 0.00005
    final_lr: 0.000049

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

    grad_clip: 3.0

checkpoint_interval: 2500
save_optimizer: false

init_hooked: false
init_hooked_steps: 0

acc_rolling_beta: 0.9
kl_rolling_beta: 0.9

base_alpha_1: 10.0
alpha_steps_1: 10000

base_alpha_2: 0.2
alpha_steps_2: 50000

upper_acc_bound: 0.80
lower_acc_bound: 0.70
min_lm_scale: 0.1

acc_hook: 0.75

ignore_kl_weights: false
kl_scale: 0.1

log_image_interval: 100
