trainer_type: zae

dataset:
    name: fineweb-100BT-split-128
    branch: split-1

    type: split
    kwargs: {}

bs: 256
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 100
    num_training_steps: 50000

    lr: 0.00005
    final_lr: 0.000005

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

checkpoint_interval: 2500
save_optimizer: false

upper_p_bound: 0.75
lower_p_bound: 0.50

acc_hook: 0.5

kl_weight: 0.01
mean_weight: 0.1
