trainer_type: zlm

dataset:
    name: fineweb-100BT-split-128
    branch: split-2

    type: zae
    kwargs:
        checkpoint_path: local_data/proto-zlm_zae-beta/000000030000

bs: 128
num_epochs: 1

optimizer_type: adamw
optimizer_kwargs:

    num_warmup_steps: 100
    num_training_steps: 20000

    lr: 0.00005
    final_lr: 0.000005

    betas: [0.9, 0.95]
    eps: 0.00000001
    weight_decay: 0.01

checkpoint_interval: 2000
save_optimizer: false

hook_kl: 5.0

running_beta: 0.9

log_image_interval: 100
